### ISSUE TITLE
Add support satellite tracking function

### ISSUE THREAD

**Issue by f4inu** [hmatuschek/qdmr#497]
Anytone 878 CPS 3.04 added a new satellite tracking function for both UV and UVII models. 

While useful, this feature is somewhat broken for some birds as the predictions are way off, like for the ISS. Some others are good.

I suspect this is because some sats move more on their orbit than others, so the orbital data (Two Line Element - aka keplerians or "keps") ages quicker.

Sat tracking software (gpredict, look4sat, ...) need to update the list of TLEs often, possibly before each use to be accurate.

I realize this is quite a bit of work to reverse-engineer such a unique feature, but it would be great if qdmr could update those parameters!

(Sorry for editing your post. But the ToDo list must be in the initial post to be shown above.)

The TLE upload is also a feature of OpenGD77 and OpenRTX. Hence I would implement it for all:

- [x] Implement orbital elements database (https://celestrak.org/NORAD/elements/gp.php?GROUP=amateur&FORMAT=json)
- [x] Implement Transmitter database (https://db.satnogs.org/api/transmitters/?format=json)
- [x] Implement editing/selection dialog for sats to upload.
- [x] Reverse engineer CP formats
  - [x] For AnyTone devices
  - [x] For OpenGD77 devices
- [x] Implement for AnyTone AT-D878UV
- [x] Implement for AnyTone AT-D878UV II
- [x] ~~Implement for AnyTone AT-D578UV~~
- [x] Implement for OpenGD77

**Comment by f4inu** [comment]
CPS & Firmware 3.05 were published two days ago on 2024/12/12 and we now have a tool to update TLEs in the radio. 
![gps_sat_data_update](https://github.com/user-attachments/assets/50030eaa-1a53-42f4-b771-67bc2198184e)

The predictions are now correct!

**Comment by hmatuschek** [comment]
Hi all. I would like to start a small discussion on how to update the orbital elements and transponder information. A preliminary implementation can be found in the  branch associated with this issue. 

I want to discuss:
1.  How to manage the information (orbital elements & transponder)
  - A proposal can be found in the `497-add-support-satellite-tracking-function` branch.
3. How to update the radio
  - Just upload the information along with the code plug
  - Provide a separate menu/toolbar item to initiate the update

**Comment by f4inu** [comment]
1) I like the "Edit satellite database" menu, it gets the job done, but I wonder how are the frequency found and selected. For example, for AO27 I was proposed the same frequencies as for SO50, but this is wrong. 

It might be needed to have a menu to update satellite transponder data, much like in gpredict. 

(oh and in satellitedatabase.cc the menu names use "Frquency" and not "Frequency". Not sure if intended or not). 

3) Anytone's original CPS has a separate menu/tool to upload the satellite configuration and I think this might be the easiest, from the user point of view at least. 
I may not want to update my codeplug at the moment but would like very much updated TLEs. 

This is something we might need to do several times a week to keep fresh enough data. Having a separate tool/menu from the codeplug will make it smoother. 

my 2cts

**Comment by hmatuschek** [comment]
Okay, making some progress here. In the associated branch, you can edit and write satellites to the D878UV. This is the only device supporting this feature for now. OpenGD77 still needs some attention.

**Comment by hmatuschek** [comment]
Implementation is done. AnyTone works, OpenGD77 is implemented but still a bit buggy.

**Comment by hmatuschek** [comment]
Should be ready. Happy testing.

**Comment by hmatuschek** [comment]
It is. The 3.05 support is still buggy but not catastrophic. The next
release (0.12.2) will update the AnyTone support anyway.

allesand ***@***.***> schrieb am So., 12. Jan. 2025, 18:42:

**Comment by f4inu** [comment]
So far, so good. Upload is swift, programming appears correct. 

A few notes:

- Selecting a sat: a bit rough, with no way to sort the birds. Could be great to be able to filter based on name or norad id.
- When selecting a frequency for a given sat, there is no way to clear the selection and get back to 'none', other than deleting the whole line. 
- CTCSS is not set automatically. Not sure if this is feasible or not. If you need an example, FOX-1B/Radfxsat uses ctcss. 

Other than that, I'm very much pleased with this patch!

**Comment by hmatuschek** [comment]
Actually, you can search. There is a somewhat hidden search feature. Just
hit Ctrl-F.

There is no reliable source for the satellite transponder info. I just can
get the frequency and mode for a NORAD id from satnogs.

f4inu ***@***.***> schrieb am Fr., 17. Jan. 2025, 15:28:
